### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method when span_info is False

### ISSUE THREAD

**Issue by blu-dragoon** [iwpnd/flashgeotext#174]
As per the doc [https://flashgeotext.iwpnd.pw/geotext/](url), the GeoText Class python function extract has an optional argument `span_info : bool` - return span_info. Defaults to True. However, on passing the span_info argument as false, GeoText fails to parse the text and throws an index slice error. 

Below are the steps to reproduce the error:

```
from flashgeotext.geotext import GeoText
geotext2 = GeoText()

input_text = '''Shanghai. The Chinese Ministry of Finance in Shanghai said that China plans
                    to cut tariffs on $75 billion worth of goods that the country
                    imports from the US. Washington welcomes the decision.'''

geotext2.extract(input_text=input_text, span_info=False)
```

Output: >    "found_as": [input_text[span_start:span_end]], TypeError: slice indices must be integers or None or have an __index__ method

**Comment by iwpnd** [comment]
Hey @blu-dragoon, haven't worked on this quite some time. Thanks for reaching out, I'll take a look in the evening. 👍

**Comment by iwpnd** [comment]
[v0.4.1](https://github.com/iwpnd/flashgeotext/releases/tag/v0.4.1) adresses and fixes the issue. Thanks for reporting! 🙏

**Comment by blu-dragoon** [comment]
> [v0.4.1](https://github.com/iwpnd/flashgeotext/releases/tag/v0.4.1) addresses and fixes the issue. Thanks for reporting! pray

Thanks, the issue is fixed and works properly now.
