### ISSUE TITLE
Countries / cities with only (or none) capitals are not recognized

### ISSUE THREAD

**Issue by MyrtheLammerse** [iwpnd/flashgeotext#182]
As you can see on both pictures, the correct country / city is only extracted and recognized if it is correctly capitalized. It would be really helpful if the package can also extract and normalize countries / cities that are formatted differently. 

<img width="947" alt="Schermafbeelding 2022-02-14 om 14 36 13" src="https://user-images.githubusercontent.com/28976122/153874233-50d9cdc2-d172-4581-a8cc-f4986922bcfd.png">

<img width="928" alt="Schermafbeelding 2022-02-14 om 14 38 34" src="https://user-images.githubusercontent.com/28976122/153874596-175e7e19-8174-4d9f-abf6-d17563b7828a.png">

**Comment by iwpnd** [comment]
The best issues are those that solve themselves @MyrtheLammerse :)
