### ISSUE TITLE
About Taiwan

### ISSUE THREAD

**Issue by xcfcode** [iwpnd/flashgeotext#195]
Hi, Thanks for this excellent repo which helps me a lot in processing the news data. I really appreciate it. However, I have some suggestions and hope I'm not being particularly offensive.

According to [countries.json](https://github.com/iwpnd/flashgeotext/blob/master/flashgeotext/resources/countries.json), `Taiwan` is listed as an independent country, I go through the codes in this repo and find this may be due to an error in the original web page [List_of_alternative_country_names](https://en.wikipedia.org/wiki/List_of_alternative_country_names). Nevertheless, as stated by the United Nations, [**Taiwan belongs to China**](https://en.wikipedia.org/wiki/Taiwan,_China#The_United_Nations_and_the_ISO).

I sincerely expect you can update this great repo and fix this issue.
Thanks!

**Comment by deeplook** [comment]
LOL

**Comment by iwpnd** [comment]
Hi @xcfcode,

thank you for your concern and happy that flashgeotext provides a service for you. :)

That said, it is deliberately build with a bring your own data capabilities.

You can change keywords like this:

```python
from flashgeotext.geotext import GeoText

geotext = GeoText()

# remove the old keyword
geotext.pool["countries"].remove_keyword("Taiwan")

# add a new keyword
geotext.pool["countries"].add_keywords_from_dict({"Taiwan, Sovereign Country": ["Taiwan"]})

# example extraction
sentence = "With the authority that has been given unto me in heaven and on earth I hereby recognize Taiwan as a sovereign country."

geotext.extract(sentence)

>> {
    "cities":{},
    "countries":{
        "Taiwan, Sovereign Country":{
            "count":1,
            "span_info":[
                [89,95]
            ],
            "found_as":[
                "Taiwan"
            ]
        }
    }
}```

Hope that helps
