### ISSUE TITLE
Publishing package on conda-forge

### ISSUE THREAD

**Issue by francbartoli** [iwpnd/flashgeotext#21]
Hi @iwpnd, this is a great package! Unfortunately, it is not available on conda-forge while flashtext can be found.
I'm building a library around it and I can only fetch packages from conda-forge so I'm wondering if you might accept PR to publish on conda-forge eventually.
For now the workaround is to embed all flashgeotext as a module statically but I would love to declare it in the dependencies.

**Comment by iwpnd** [comment]
Hi @francbartoli, I'd be happy to accept your PR on this. I'd learn a thing or do I believe. :)

**Comment by francbartoli** [comment]
Hi @iwpnd, sorry for the late follow up on this. I'm now ready to perform it so I'm going to start the procedure.

By the way, I've just published [pyflashtext](https://github.com/francbartoli/pyflashtext) to [conda-forge](https://anaconda.org/conda-forge/pyflashtext), which is a fork of the original **flashtext**. I had to take this decision because the codebase contained the fuzzy search but the maintainer wasn't able to publish a new version of the package for a long time (see [this issue](https://github.com/vi3k6i5/flashtext/issues/111)).

I'd like to integrate the fuzzy search functionality as optional to flashgeotext, what do you think?

**Comment by francbartoli** [comment]
I've started the pull request for conda-forge https://github.com/conda-forge/staged-recipes/pull/14513.

@iwpnd can you please post a comment there to just say you are willing to be listed as maintainer?

**Comment by iwpnd** [comment]
I followed the discussion around the fuzzy search. Sounds like a good addition but would decrease performance depending on the edit distance? Would've to be an option in this case.

**Comment by iwpnd** [comment]
@francbartoli done

**Comment by francbartoli** [comment]
Our [feedstock repo](https://github.com/conda-forge/flashgeotext-feedstock) has been created on the conda-forge organization and the [package](https://anaconda.org/conda-forge/flashgeotext) is available to install in conda.

@iwpnd you can review the pr at your earliest convenience and then close this once that is merged.
